[package]
name = "retk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object = { version = "0.29", features = ["pe"] }
iced-x86 = "1.17"
smallvec = "1.11"
colored = "2.0"
